### ISSUE TITLE
Binarydetector should also find protrusions/indentations in holes/islands

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/LargeScaleImaging#10]
The function get_protrusions in the module binarydetector now only finds protrusions in the outer boundary of a significant connected component. It should also find protrusions on the nested boundary. See for example the [nested image](https://github.com/NLeSC/LargeScaleImaging/tree/master/TestData/Binary/MATLAB_results/Binary_nested)

**Comment by dafnevk** [comment]
Compared with the matlab code, the python detector doesn't use the large and small SE in the same way as the matlab detector, resulting in different salient regions. We need to find out why and make some choices here.

**Comment by dafnevk** [comment]
It seems that protrusions are (more or less) correct.
Indentations are not, so apparenatly in Matlab, the indentations are not equal to the protrusions of the inverse image. Is this desired?

**Comment by elboyran** [comment]
I meant to assign both of us, maybe it's not possible -)

**Comment by elboyran** [comment]
I find the cv2 figures not useful for debugging. Can't we use simply matplotlib and subplots?

**Comment by elboyran** [comment]
The indentations and protrusions are computed using Black and White top hats. For the nested regions, there is a difference weather we process ind/protr in respect to holes or islands (you found that bug and I fixed the MATLAB code). Please look at https://github.com/NLeSC/LargeScaleImaging/blob/master/Software/MATLAB/AfineRegions/Detectors/Generic/binary_detector.m and the code between lines 213 and 273 and note the difference of how SCCH (Significant CCs from Holes) and SCCI (SCC from Islands) are processed.

**Comment by dafnevk** [comment]
We decided to now only use one (large) structuring element for all types of protrusions and indentations.

**Comment by dafnevk** [comment]
There is now one pixel difference between the matlab indentations and python indentations for the nested image ;) I will close this issue now, but we should make some tests for corner cases.
