### ISSUE TITLE
fix MATLAB code for nested protrusions/indentations; generate correct nested results

### ISSUE THREAD

**Issue by elboyran** [NLeSC/LargeScaleImaging#11]

**Comment by elboyran** [comment]
I fixed the indentations and protrusions in relations to large holes and also removed those touching the image borders. After that I regenerated again the test results with slightly different parameters (nested looks nicer) - sorry ;-)
Below are the values
SE_size_factor =    0.0750
Area_factor =    0.0500
conn =     4
And for nested image, these are the other parameters
SE_size =    10
SEhi_size =     5
lambda =    50
lambdahi =     5

**Comment by dafnevk** [comment]
Could you also export the matfile for the Structuring Element that was used here? I assumed it changed (since I get different results now).

**Comment by elboyran** [comment]
I've pushed SE_n.mat

**Comment by elboyran** [comment]
it corresponds to
test_image =nested
SE_size_factor =    0.0750
Area_factor =    0.0500
conn =     4
SE_size =    16
SEhi_size =     8
lambda =    80
lambdahi =     8

The nested file is a bit larger (400x400) than the other test files (256x256). Do you want their SE as well?

**Comment by dafnevk** [comment]
Yes, please because the test is now written for the 'all_types_noise' image.

**Comment by dafnevk** [comment]
And, especially for the nested image, also the SEhi (the small Structuring Element).

**Comment by elboyran** [comment]
Ah, yes, sure. I'll generate them now.

**Comment by elboyran** [comment]
Commited.

**Comment by elboyran** [comment]
Committed results for nested only with 1 SE.
