### ISSUE TITLE
Make detector for grey/color  images

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/LargeScaleImaging#14]
Make class salientregions_detector that provides functionality to find salient regions for grey scale and color images. 
For grey scale images, use OTSU binarization.
For color images, first convert to grey scale.

**Comment by elboyran** [comment]
For gray images, I'd also like to have "my method" (described in the submitted paper) implemented :-)

**Comment by dafnevk** [comment]
I agree, but let's make it a different issue.
