### ISSUE TITLE
Write function to output file with ellipses

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/LargeScaleImaging#21]
In order to evaluate the quality of the salient regions, we need to output the salient regions as files containing the coordinates and parameter of the corresponding ellipses.
Part of the code (see comments) should be equivalent to the matlab code in binary_mask2features.m.

**Comment by elboyran** [comment]
Write a helper function  which converts axis lengths and angle to polynomial coefficients. The code should be equivalent to conversion_ellipse.m

**Comment by elboyran** [comment]
Write a helper function which computes the ellipse features (coefficients) from a binary mask of 1 region type (holes|islands|indentations|protrusions). This code should be equivalent to the matlab code in binary_mask2features.m.

**Comment by elboyran** [comment]
cv2.connectedComponentsWithStats doesn't give enough statistics needed for the region to ellipse representation, e.g. no axis length or orientation.

**Comment by dafnevk** [comment]
I also came across the function [fitellipse](http://docs.opencv.org/3.0-beta/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html#fitellipse) , is that of any help?

**Comment by elboyran** [comment]
Not exactly. We actually don't need the ellipse itself, but rather some measurements of  the region, namely defined as:
'MajorAxisLength'	Returns a scalar that specifies the length (in pixels) of the major axis of the ellipse that has the same normalized second central moments as the region.	
'MinorAxisLength'	Returns a scalar that specifies the length (in pixels) of the minor axis of the ellipse that has the same normalized second central moments as the region.	
'Orientation'	Returns a scalar that specifies the angle between the x-axis and the major axis of the ellipse that has the same second-moments as the region.

**Comment by elboyran** [comment]
I think we need code like this one: http://opencvpython.blogspot.nl/2012/04/contour-features.html

**Comment by elboyran** [comment]
it seems it might be as simple as
 (x,y),(MA,ma),angle = cv2.fitEllipse(cnt)

**Comment by dafnevk** [comment]
Issue moved to [NLeSC/SalientDetector-python #5](https://github.com/NLeSC/SalientDetector-python/issues/5) via [**ZenHub.io**](https://www.zenhub.io/)
