### ISSUE TITLE
Migrate python code to separate repository

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/LargeScaleImaging#27]
It would be better to separate the python and matlab code, since they are completely independant.

**Comment by dafnevk** [comment]
See: http://stackoverflow.com/questions/2538245/extract-part-of-a-git-repository

**Comment by dafnevk** [comment]
And: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by dafnevk** [comment]
Because this is an eStep project, the new repository needs to go under the NLeSC organisation. We can request a new repo by making an office IT issue.

**Comment by dafnevk** [comment]
Done!

**Comment by dafnevk** [comment]
I also moved the open issues to the new repository.

**Comment by dafnevk** [comment]
In step six of [this manual](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/), I had to do:
`git remote set-url origin <url-of-new-repo>`

**Comment by elboyran** [comment]
Problem with unstages changes. Posted in HelpWanted.
