### ISSUE TITLE
Install CV2 and describe the installation

### ISSUE THREAD

**Issue by elboyran** [NLeSC/LargeScaleImaging#3]

**Comment by elboyran** [comment]
It might be not so easy, here's a [tutorial]( http://www.askaswiss.com/2016/01/how-to-install-opencv-3-1-python-ubuntu-14-04.html) on how to install the latest version3.1. on Ubuntu 14.04LTS.

**Comment by dafnevk** [comment]
It should also be possible with this command:
`conda install -c https://conda.anaconda.org/menpo opencv`

**Comment by elboyran** [comment]
I have installed Anaconda and the OpenCV with this command, seems to work for me!

**Comment by elboyran** [comment]
Do we consider that issue done? :-) Is the only line your comment from 10 days ago? Where would we put such installation instructions?

**Comment by dafnevk** [comment]
Let's close this issue, I will make a new issue to properly describe installation.

**Comment by dafnevk** [comment]
To install opencv version 3.1.0:
conda install -c https://conda.anaconda.org/menpo opencv3
