### ISSUE TITLE
Prepare images and masks in Matlab for testing

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/LargeScaleImaging#34]
In order to test the SalientDetector (issue #20) we need the binary masks of the regions for 2 test images: one grayscale image, one color image.

**Comment by elboyran** [comment]
DMSRA and MSSRA regions are detected on 2 images- gray and color. Also the MATLAB elliptical plots are saved (for sanity check).
The parameters used are:
MSSRA:
----------
    saliency_types = [1 1 1 1];
    SE_size_factor = 0.02;
    Area_factor = 0.03;
    num_levels = 20;
    thresh = 0.6;
    thresh_type = 's';
**************************************************************
DMSRA:
----------
    SE_size_factor = 0.02;
    Area_factor_very_large = 0.01;
    Area_factor_large = 0.001;
    lambda_factor = 3;
    num_levels = 255;
    offset = 80;
    otsu_only = false;
    conn = 8;
    weight_all = 0.33;
    weight_large = 0.33;
    weight_very_large = 0.33;
    saliency_type = [1 1 1 1];

**Comment by elboyran** [comment]
To be dealt with in the Python repo.
