### ISSUE TITLE
Migrate the MATLAB code in a separate repository

### ISSUE THREAD

**Issue by elboyran** [NLeSC/LargeScaleImaging#36]

**Comment by elboyran** [comment]
Look athow Dafne did it for the Python code in issue #27 .

**Comment by dafnevk** [comment]
Don't forget to also copy the LICENSE file.

**Comment by elboyran** [comment]
Problem with unstages changes. Posted in HelpWanted.

**Comment by elboyran** [comment]
It failed in step 6 (also using your additional command) from https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/.

elena@elena-VirtualBox:~/eStep/LargeScaleImaging$ git filter-branch --prune-empty --subdirectory-filter ./Software/MATLAB/AfineRegions/Detectors/ master
Rewrite 4a603bbc445a83751efa7cef9e8aba0466888716 (259/259)
Ref 'refs/heads/master' was rewritten
warning: unable to unlink Publications/StateOfTheArt/2011_Dickscheid_Schindler_Forstner_Coding_ijcv.pdf: Operation not permitted
elena@elena-VirtualBox:~/eStep/LargeScaleImaging$ git remote set-url origin https://github.com/NLeSC/SalientDetector-matlab
elena@elena-VirtualBox:~/eStep/LargeScaleImaging$ git push origin .
fatal: remote part of refspec is not a valid name in .
Unexpected end of command stream

Could you, please, take over?
The subfolder is ./Software/MATLAB/AfineRegions/Detectors/ .

**Comment by elboyran** [comment]
I'm afraid my attempt seems to have messed up the repo somehow Now I try to clone it clean and it does only part of Data folder! I really struggle with git.

**Comment by dafnevk** [comment]
I think your push command wasn't correct, I did:
`git push -u origin master `
and that worked.

**Comment by elboyran** [comment]
Nice, that is worked now, thanks!
Now issue #37 https://github.com/NLeSC/LargeScaleImaging/issues/37 can be fixed.
I thought the  issues will also move to the new repo, but they are not so many..

**Comment by elboyran** [comment]
Did you have any errors while moving the sub-directory to the new repo? Now all the files which remained in the Data folder in this repo are corrupted and cannot be opened.
