### ISSUE TITLE
Write tests for helper function binarize

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/LargeScaleImaging#6]
We want to have a unit test for the function binarize (in the helpers module).
This function should test the correct behavior for a specific test image.

**Comment by elboyran** [comment]
The nosetests on my VM (Linux on WIndows host) in the shared folder works only with --exe flag (cant change the file permissions!), Also verbose is useful, so the command to use is
nosetests tests/ -v --exe

**Comment by dafnevk** [comment]
It seems strange and undesired to me that the files are executable on your system, and that you can't change it.
Is git maybe not tracking it correctly? See:
http://stackoverflow.com/questions/3821263/what-does-git-think-a-files-executable-bits-value-is
http://superuser.com/questions/300601/why-git-keeps-track-of-changes-in-execution-permission/300615

Maybe it has to do with the fact it's in the shared folder with Windows...

**Comment by elboyran** [comment]
"Maybe it has to do with the fact it's in the shared folder with Windows..."
I'm afraid so.

**Comment by elboyran** [comment]
Done. Flag "visualize" has been misspelled, corrected  some places only (affected by the tests), might need to fix the rest.

**Comment by elboyran** [comment]
Test for a different threshold than 128.

**Comment by elboyran** [comment]
Something very weird is going on. I made several more tests (for different threshold levels) and it passes them all, but for level 130. In MATLAB the rule I use is "binary = gray>= level", while it seems opencv uses "binary = gray > thresh". Still changing MATLAB code for level 130  to >, not >= still doesn't help and this particular test fails!??

**Comment by elboyran** [comment]
Fix the MATLAB code to use > not >=. Try all tests again.

**Comment by elboyran** [comment]
MATLAB code fixed. 4 binarization tests for levels 0, 57, 175 and 255 committed.
